acme_store:
    resource: "@AcmeStoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation


app_client:
    path:     /app/client
    defaults: { _controller: AcmeStoreBundle:Client:index }


app_user:
    path:     /app/{slug}
    defaults: { _controller: AcmeStoreBundle:User:index }